print("Python program on tuple")
tuple1 = (10,50,20,40,30)
print("To display the elements in a tuple : ")
print(tuple1)
print("To display the elements 10 and 50 from tuple1")
print(tuple1[0:2])
print("To display the length of a tuple1")
print(len(tuple1))
print("To find the minimum element from tuple1")
print(min(tuple1))
print("To add all elements in the tuple1")
print(tuple1 * 2)
print(tuple1 + tuple1)
print("To display same tuple1 multiple times")
print(tuple1 * 3)